### ISSUE TITLE
`grunt serve` causes UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by davewood** [certat/do-portal#123]
```
Running "watch" task
Waiting...
(node:124) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/cert/customer-portal/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

(node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/bpmn-io/bpmn-js-examples/issues/34
https://stackoverflow.com/questions/34596085/grunt-watch-fails-with-message-running-watch-task-waiting-warning-maximu

**Comment by davewood** [comment]
caused by 3rd party module "opn". waiting for frontend rework.
