### ISSUE TITLE
FATAL:  password authentication failed for user "do_portal"

### ISSUE THREAD

**Issue by skenfilip** [certat/do-portal#132]
Hi, i'm trying to install do_portal and every line from the install tutorial has finished successfully until "python manage.py db migrate;", which gives me the following error:

```
Traceback (most recent call last):
  File "manage.py", line 276, in <module>
    cli()
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/flask/cli.py", line 251, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/flask_migrate/cli.py", line 88, in migrate
    rev_id)
  File "/home/cert/do-portal/lib/python3.5/site-packages/flask_migrate/__init__.py", line 177, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/cert/do-portal/lib/python3.5/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/home/cert/do-portal/lib/python3.5/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/cert/do-portal/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/cert/do-portal/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 817, in load_module
  File "<frozen importlib._bootstrap_external>", line 676, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/cert/do-portal/backend/misc/migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "/home/cert/do-portal/backend/misc/migrations/env.py", line 72, in run_migrations_online
    connection = engine.connect()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/cert/do-portal/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/cert/do-portal/lib/python3.5/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "do_portal"
FATAL:  password authentication failed for user "do_portal"
```
I've been stuck with this problem for 2-3 days so if possible please someone help.

**Comment by MarkHofstetter** [comment]
Hi, are you able to access the postgres database via psql?

**Comment by skenfilip** [comment]
Thanks for the quick response. I'm able to access postgres db. Here is screenshot from my users and databases in postgres:
![image](https://user-images.githubusercontent.com/37016168/87041822-157dc880-c1f3-11ea-9bee-bcb2d06761d7.png)

**Comment by skenfilip** [comment]
It's okay i managed to fix the issue, it is very good written that we should "Create the PostgreSQL Database and User matching with the configuration.". Database name: do_portal, username: do_portal, but i skipped that part :) Thank you for your response.

**Comment by MarkHofstetter** [comment]
just out off pure interest what are you planing to use the software for?

**Comment by skenfilip** [comment]
I'm trying to connect it to intelmq and see how the whole picture looks, i haven't read the whole documentation to see how it helps for intelmq, but it looks like something that i might need.

**Comment by wagner-certat** [comment]
> I'm trying to connect it to intelmq and see how the whole picture looks, i haven't read the whole documentation to see how it helps for intelmq, but it looks like something that i might need.

If you reveal what you need, we could help :) You can ask us on the mailing list (see https://github.com/certtools/intelmq/#user-content-user-guide) or reach me directly at wagner@cert.at

**Comment by skenfilip** [comment]
I will have that in mind, big tumbs up for your involvement in the
resolving issues.

**Comment by wagner-certat** [comment]
Please note, that we do currently not plan to further develop this software-stack, but only maintain it for the near future. It is intended to do a rewrite for the same and wider intended use.

**Comment by wagner-certat** [comment]
@skenfilip This software is now in maintenance mode, more information here: https://github.com/certat/do-portal/issues/133
