### ISSUE TITLE
Can't edit organization details

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#39]
When changing organization details (Name, Abbreviation) I get a 502 Bad Gateway.
![do-portal-screenshot_2018-10-18_16-34-35](https://user-images.githubusercontent.com/25031221/47162152-bb88f100-d2f3-11e8-815b-e604bdbb4557.png)

**Comment by certrik** [comment]
Please fix before release-aec.

**Comment by davewood** [comment]
```
Traceback (most recent call last):
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/flask_jsonschema.py", line 80, in decorated
    return fn(*args, **kwargs)
  File "./app/cp/organizations.py", line 439, in update_cp_organization
    o.from_json(request.json)
  File "./app/models.py", line 142, in from_json
    setattr(self, attr, value)
  File "/home/cp-server/do-portal/lib/python3.4/site-packages/sqlalchemy/ext/hybrid.py", line 746, in __set__
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute
[pid: 9865|app: 0|req: 3/9] xxx.xxx.xxx.xxx () {56 vars in 1274 bytes} [Mon Oct 22 11:08:45 2018] PUT /cp/1.0/organizations/3 => generated 0 bytes in 273 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by MarkHofstetter** [comment]
fixed in 1dafbc99b62d361888ea104728ab80925b6fa381

this bug only shows up in the web context, neither the model nor the api endpoint tests showed this behavior => make web end2end tests

waiting for @wagner-certat  to remove the release branch protection for deployment

**Comment by wagner-certat** [comment]
Could you please push the commit to a branch or open a PR to the release branch?

**Comment by MarkHofstetter** [comment]
you're welcome, new branch:

topic-fix-issue-39




Am 29.10.2018 um 14:37 schrieb Wagner:
