### ISSUE TITLE
mailmanclient incompatible with Python3.4

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#43]
```
Obtaining mailmanclient from git+https://gitlab.com/mailman/mailmanclient#egg=mailmanclient (from -r requirements.txt (line 44))
  Cloning https://gitlab.com/mailman/mailmanclient to ./src/mailmanclient
    Complete output from command python setup.py egg_info:
    Python 3.5.0 or better is required�
    88% |�����������������������������
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/cp-server/do-portal/src/mailmanclient/
```

We are using Python 3.4

This is a release blocker.

**Comment by wagner-certat** [comment]
not installing mailmanclient gives:

```
Traceback (most recent call last):
  File "/home/cp-server/do-portal/manage.py", line 15, in <module>
    from app.models import User, Organization, IpRange, Fqdn, Asn, Email
  File "./app/models.py", line 10, in <module>
    from mailmanclient import MailmanConnectionError, Client
ImportError: No module named 'mailmanclient'
Tue Oct 30 13:55:17 2018 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Oct 30 13:55:17 2018 - *** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/cp-server/do-portal/manage.py", line 15, in <module>
    from app.models import User, Organization, IpRange, Fqdn, Asn, Email
  File "./app/models.py", line 10, in <module>
    from mailmanclient import MailmanConnectionError, Client
ImportError: No module named 'mailmanclient'
Tue Oct 30 13:55:17 2018 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Oct 30 13:55:17 2018 - *** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/cp-server/do-portal/manage.py", line 15, in <module>
    from app.models import User, Organization, IpRange, Fqdn, Asn, Email
  File "./app/models.py", line 10, in <module>
    from mailmanclient import MailmanConnectionError, Client
ImportError: No module named 'mailmanclient'
Tue Oct 30 13:55:17 2018 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Oct 30 13:55:17 2018 - *** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/cp-server/do-portal/manage.py", line 15, in <module>
    from app.models import User, Organization, IpRange, Fqdn, Asn, Email
  File "./app/models.py", line 10, in <module>
    from mailmanclient import MailmanConnectionError, Client
```

**Comment by wagner-certat** [comment]
Using current stable mailmanclient 3.2.0 works
