### ISSUE TITLE
Calling /api/1.0/ripe/contact gives 500

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#71]
Throws an exception. From the logs:
```
Traceback (most recent call last):
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/cp/fody.py", line 60, in get_cp_contact_for_netblock
    cidr = unquote(cidr)
  File "/usr/lib/python3.4/urllib/parse.py", line 519, in unquote
    if '%' not in string:
TypeError: argument of type 'NoneType' is not iterable
[pid: 4492|app: 0|req: 105/436] 83.136.38.239 () {48 vars in 1225 bytes} [Thu Mar 21 17:41:55 2019] GET /cp/1.0/ripe/contact => generated 0 bytes in 80 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0)
```
Should be handled.

**Comment by MarkHofstetter** [comment]
fixed in 3eba9d51cf8a355ab1a4413603e8a1dee4d25d12
