### ISSUE TITLE
Statistics broken if a handle is gone

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#82]
Blank page is shown, see current staging.

From the logs:
```
Traceback (most recent call last):
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cp-server/do-portal/backend/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/cp/grafana.py", line 62, in get_grafana
    a = FodyOrganization(r.ripe_org_hdl).asns
  File "./app/models.py", line 981, in __init__
    raise AttributeError('no such handle', ripe_org_hdl)
AttributeError: ('no such handle', 'ORG-MAA1-RIPE')
```

**Comment by MarkHofstetter** [comment]
I guess this is duplicate
